camel:
  health:
    enabled: true
    routes-enabled: true
  component:
    rabbitmq:
      hostname: localhost
      port-number: 5672
      username: guest
      password: guest
  springboot:
    main-run-controller: true

spring:
  application:
    name: iroha-balancer
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: itps-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: iroha-balancer-scheduling-
      pool:
        size: 2
  rabbitmq:
    host: ${camel.component.rabbitmq.hostname}
    port: ${camel.component.rabbitmq.port-number}
    username: ${camel.component.rabbitmq.username}
    password: ${camel.component.rabbitmq.password}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  health:
    rabbit:
      enabled: true
    mail:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

iroha:
  peers: iroha1.tst2.bakong.soramitsu.co.jp:50051,iroha2.tst2.bakong.soramitsu.co.jp:50051,iroha3.tst2.bakong.soramitsu.co.jp:50051,iroha4.tst2.bakong.soramitsu.co.jp:50051

